# Add permission to list the POD for in cluster PODs
{{- if .Values.cno }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vkaci.fullname" . }}-pods-list
  labels:
    {{- include "vkaci.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services", "nodes", "pods"]
  verbs: ["list", "get"]
- apiGroups: ["crd.projectcalico.org"]
  resources: ["bgpconfigurations"]
  verbs: ["list","get"]
- apiGroups: ["cilium.io"]
  resources: ["ciliumbgppeeringpolicies"]
  verbs: ["list","get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vkaci.fullname" . }}-pods-list
  labels:
    {{- include "vkaci.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "vkaci.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "vkaci.fullname" . }}-pods-list
  apiGroup: rbac.authorization.k8s.io
{{- end }}