# Add permission to list the nodefabricnetworkattachments
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "vkaci.fullname" . }}-nodefabricnetworkattachments-reader"
  labels:
    {{- include "vkaci.labels" . | nindent 4 }}
  namespace: aci-containers-system
rules:
  - apiGroups: ["aci.fabricattachment"]
    resources: ["nodefabricnetworkattachments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "vkaci.fullname" . }}-nodefabricnetworkattachments-binding"
  labels:
    {{- include "vkaci.labels" . | nindent 4 }}
  namespace: aci-containers-system
subjects:
  - kind: ServiceAccount
    name: {{ include "vkaci.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role # this must be Role or ClusterRole
  name: {{ include "vkaci.fullname" . }}-nodefabricnetworkattachments-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
