apiVersion: v1
kind: Service
metadata:
  name: {{ include "vkaci.fullname" .}}
  labels:
    {{- include "vkaci.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  #externalIPs:
  #  - {{ .Values.service.externalIP }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | default "Cluster" }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
  {{- end }}
  ports:
    - port: 80
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "vkaci.selectorLabels" . | nindent 4 }}
