apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vkaci.fullname" . }}-aci-user-cert
  labels:
    {{- include "vkaci.labels" . | nindent 4 }}
data:
  user.key: {{ .Values.apicKeyData }}
# The pod, the init container will put the aci metadata in the /root/.aci-meta folder so that pyACI has it locally. 
# User needs to set the list of APIC IPs (for both containers) and the name of the APIC certificate and the user that is associated to it.